#Breast Cancer Detection using Artificial Neural Network
1. Deep Neural Network (DNN)


Aim: To implement Neural Network for a classification problem

In [ ]:
 #importing all required libraries
import keras
from keras import Sequential
from keras.layers import Flatten, Dense, Dropout, BatchNormalization , Conv1D, MaxPool1D
from keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.optimizers import Adam
print('The required libraries for the ANN has been imported from the keras')

The required libraries for the ANN has been imported from the keras


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

Loading the Breast Cancer dataset. The Description of the dataset is as follows:


In [ ]:
df = pd.read_csv('/content/data (2).csv')
df.head

<bound method NDFrame.head of            id diagnosis  ...  symmetry_worst  fractal_dimension_worst
0      842302         M  ...          0.4601                  0.11890
1      842517         M  ...          0.2750                  0.08902
2    84300903         M  ...          0.3613                  0.08758
3    84348301         M  ...          0.6638                  0.17300
4    84358402         M  ...          0.2364                  0.07678
..        ...       ...  ...             ...                      ...
564    926424         M  ...          0.2060                  0.07115
565    926682         M  ...          0.2572                  0.06637
566    926954         M  ...          0.2218                  0.07820
567    927241         M  ...          0.4087                  0.12400
568     92751         B  ...          0.2871                  0.07039

[569 rows x 32 columns]>

In [ ]:
#defining indexes of the dataframes
X = df.iloc[:, 2:32].values #selecting all the rows and columns 2-32
Y = df.iloc[:,1].values #all rows and 1st column

In [ ]:
X

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [ ]:
Y

array(['M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'B', 'B', 'B', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'B', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'B', 'M', 'B', 'B', 'B', 'B',
       'B', 'M', 'M', 'B', 'M', 'M', 'B', 'B', 'B', 'B', 'M', 'B', 'M',
       'M', 'B', 'B', 'B', 'B', 'M', 'B', 'M', 'M', 'B', 'M', 'B', 'M',
       'M', 'B', 'B', 'B', 'M', 'M', 'B', 'M', 'M', 'M', 'B', 'B', 'B',
       'M', 'B', 'B', 'M', 'M', 'B', 'B', 'B', 'M', 'M', 'B', 'B', 'B',
       'B', 'M', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'M', 'M', 'M', 'B', 'M', 'M', 'B', 'B', 'B', 'M', 'M', 'B', 'M',
       'B', 'M', 'M', 'B', 'M', 'M', 'B', 'B', 'M', 'B', 'B', 'M', 'B',
       'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'M', 'B', 'B', 'B', 'B', 'M', 'M', 'B', 'M', 'B', 'B', 'M', 'M',
       'B', 'B', 'M', 'M', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'M

In [ ]:
from sklearn.preprocessing import LabelEncoder
labelencoder_Y = LabelEncoder()
Y = labelencoder_Y.fit_transform(Y)

X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.2, random_state = 0)

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

print('The data type of the actual data', type(df))
print('The data type pf X and Y is',type(X))

The data type of the actual data <class 'pandas.core.frame.DataFrame'>
The data type pf X and Y is <class 'numpy.ndarray'>


In [ ]:
Y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,

In [ ]:
X_train

array([[-1.15036482, -0.39064196, -1.12855021, ..., -0.75798367,
        -0.01614761, -0.38503402],
       [-0.93798972,  0.68051405, -0.94820146, ..., -0.60687023,
         0.09669004, -0.38615797],
       [ 0.574121  , -1.03333557,  0.51394098, ..., -0.02371948,
        -0.20050207, -0.75144254],
       ...,
       [-1.32422924, -0.20048168, -1.31754581, ..., -0.97974953,
        -0.71542314, -0.11978123],
       [-1.24380987, -0.2245526 , -1.28007609, ..., -1.75401433,
        -1.58157125, -1.00601779],
       [-0.73694129,  1.14989702, -0.71226578, ..., -0.27460457,
        -1.25895095,  0.21515662]])

In [ ]:
X_test

array([[-0.20175604,  0.3290786 , -0.13086754, ...,  1.3893291 ,
         1.08203284,  1.54029664],
       [-0.25555773,  1.46763319, -0.31780437, ..., -0.83369364,
        -0.73131577, -0.87732522],
       [-0.02619262, -0.8407682 , -0.09175081, ..., -0.49483785,
        -1.22080864, -0.92115937],
       ...,
       [ 1.71811488,  0.09318356,  1.7286186 , ...,  1.57630515,
         0.20317063, -0.15406178],
       [ 1.18859296,  0.34352115,  1.19333694, ...,  0.56019755,
         0.26991966, -0.27320074],
       [ 0.26263752, -0.58080224,  0.28459338, ..., -0.19383705,
        -1.15564888,  0.11231497]])

In [ ]:
model_NN = Sequential()

#Add an input layer
model_NN.add(Dense(30,activation='relu', input_shape=(30,)))

#Add hidden layer (1st,2nd,3rd,4th)
model_NN.add(Dense(16,activation='relu'))
model_NN.add(Dense(8,activation='relu'))

model_NN.add(Dense(4,activation='relu'))

model_NN.add(Dense(2,activation='relu'))

#Add an output layer
model_NN.add(Dense(1, activation = 'sigmoid'))


In [ ]:
model_NN.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 30)                930       
                                                                 
 dense_1 (Dense)             (None, 16)                496       
                                                                 
 dense_2 (Dense)             (None, 8)                 136       
                                                                 
 dense_3 (Dense)             (None, 4)                 36        
                                                                 
 dense_4 (Dense)             (None, 2)                 10        
                                                                 
 dense_5 (Dense)             (None, 1)                 3         
                                                                 
Total params: 1,611
Trainable params: 1,611
Non-trainabl

Model is compiled with layer information taken above and with optimizer adam which is used for the gradient decent algorithm and learning rate. Since our final classification in the form of either cancer Malignet or Bigne so we have considered over here Binary cross entropy loss and metrics as accuracy

In [ ]:
model_NN.compile(optimizer = 'Adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

Finally the Deep Neural Netwrok is trained with help pf training data and also tested with testing data. The epoches here ar 150

In [ ]:
model = model_NN.fit(X_train, Y_train, epochs = 150, validation_data = (X_test, Y_test), verbose = 1, batch_size=1)

Epoch 1/150
455/455 [==============================] - 2s 3ms/step - loss: 0.3749 - accuracy: 0.8220 - val_loss: 0.3356 - val_accuracy: 0.9211
Epoch 2/150
455/455 [==============================] - 1s 2ms/step - loss: 0.2741 - accuracy: 0.9648 - val_loss: 0.3108 - val_accuracy: 0.9298
Epoch 3/150
455/455 [==============================] - 1s 2ms/step - loss: 0.2296 - accuracy: 0.9824 - val_loss: 0.2963 - val_accuracy: 0.9649
Epoch 4/150
455/455 [==============================] - 1s 2ms/step - loss: 0.2034 - accuracy: 0.9824 - val_loss: 0.2792 - val_accuracy: 0.9649
Epoch 5/150
455/455 [==============================] - 1s 2ms/step - loss: 0.1627 - accuracy: 0.9868 - val_loss: 0.2846 - val_accuracy: 0.9649
Epoch 6/150
455/455 [==============================] - 1s 2ms/step - loss: 0.1497 - accuracy: 0.9824 - val_loss: 0.2590 - val_accuracy: 0.9474
Epoch 7/150
455/455 [==============================] - 1s 2ms/step - loss: 0.1235 - accuracy: 0.9868 - val_loss: 0.2548 - val_accuracy: 0.9649

#Confusion Matrix and Classification of DNN

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
DNN_pred = model_NN.predict(X_test)
DNN_pred = (DNN_pred>0.5)
print('The confusion matrix of Logistic Regression\n', confusion_matrix(Y_test,DNN_pred))
print('The classification report of Logistic Regression is\n', classification_report(Y_test, DNN_pred))

The confusion matrix of Logistic Regression
 [[64  3]
 [ 0 47]]
The classification report of Logistic Regression is
               precision    recall  f1-score   support

           0       1.00      0.96      0.98        67
           1       0.94      1.00      0.97        47

    accuracy                           0.97       114
   macro avg       0.97      0.98      0.97       114
weighted avg       0.98      0.97      0.97       114

