In [ ]:
import keras 
from keras import Sequential 
from keras.layers import Flatten, Dense, Dropout, BatchNormalization, Conv1D,MaxPool1D
from keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.optimizers import Adam
print('The Required libraries for the ANN has been imported from the keras') 

The Required libraries for the ANN has been imported from the keras


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
from sklearn import datasets,metrics
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [ ]:
from sklearn.datasets import load_boston #importing the boston dataset from the sk learn library #load boston is a function and .data and.traget are its methods b
boston=load_boston() #storing the dataset in boston variable
X=boston.data
Y=boston.target

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.

NameError: ignored

In [ ]:
X

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [ ]:
Y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [ ]:

from sklearn.model_selection import train_test_split 
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size= 0.2, random_state= 0)


from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

print('The data type of actual data',type(boston))
print('The data type of the X and Y is',type(X))


The data type of actual data <class 'sklearn.utils.Bunch'>
The data type of the X and Y is <class 'numpy.ndarray'>


In [ ]:
Y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [ ]:
X_train

array([[-0.37257438, -0.49960763, -0.70492455, ..., -0.48463784,
         0.3716906 , -0.41100022],
       [-0.39709866, -0.49960763, -0.04487755, ...,  0.33649132,
         0.20501196, -0.38768057],
       [-0.402693  ,  0.77116771, -0.88675963, ..., -0.84958414,
         0.36660893, -0.18191902],
       ...,
       [-0.39805586, -0.49960763, -0.15941933, ..., -0.30216469,
         0.40342278, -0.33006734],
       [-0.38842357, -0.49960763, -0.60326872, ..., -0.25654641,
         0.38343489,  0.8359148 ],
       [-0.39951258, -0.49960763, -1.01275558, ..., -0.84958414,
         0.43041207,  0.27212814]])

In [ ]:
X_test

array([[-0.40835869, -0.49960763, -1.12872913, ..., -0.71272928,
         0.18547577, -0.73610347],
       [ 0.71925111, -0.49960763,  0.9988844 , ...,  0.79267419,
         0.0831649 , -0.4356916 ],
       [-0.40257488, -0.49960763,  0.39610829, ..., -0.94082071,
         0.39472748, -0.30263246],
       ...,
       [-0.3982601 ,  0.55937182, -0.85812418, ...,  0.56458276,
         0.41019833,  0.06087961],
       [-0.39934279, -0.49960763, -0.07637654, ...,  0.0627816 ,
         0.30517724, -0.45626776],
       [-0.40088071, -0.49960763, -0.36702631, ...,  1.1120022 ,
         0.41166637, -0.05983383]])

In [ ]:
X.shape

(506, 13)

In [ ]:
model_NN = Sequential()

#Add input layers
model_NN.add(Dense(13,input_shape=(13,)))
#add hidden layer

model_NN.add(Dense(6, activation='relu'))

model_NN.add(Dense(2, activation='relu'))


#Add output layer
model_NN.add(Dense(1, activation='linear'))

In [ ]:
from tensorflow.keras.losses import MeanSquaredLogarithmicError
msle = MeanSquaredLogarithmicError()
model_NN.compile(optimizer='Adam', loss=msle, metrics=[msle])

In [ ]:
model = model_NN.fit(X_train,Y_train, epochs=150, validation_data=(X_test,Y_test), verbose=1, batch_size=1)

Epoch 1/150
404/404 [==============================] - 1s 2ms/step - loss: 0.0137 - mean_squared_logarithmic_error: 0.0137 - val_loss: 0.0508 - val_mean_squared_logarithmic_error: 0.0508
Epoch 2/150
404/404 [==============================] - 1s 2ms/step - loss: 0.0135 - mean_squared_logarithmic_error: 0.0135 - val_loss: 0.0488 - val_mean_squared_logarithmic_error: 0.0488
Epoch 3/150
404/404 [==============================] - 1s 2ms/step - loss: 0.0135 - mean_squared_logarithmic_error: 0.0135 - val_loss: 0.0529 - val_mean_squared_logarithmic_error: 0.0529
Epoch 4/150
404/404 [==============================] - 1s 2ms/step - loss: 0.0140 - mean_squared_logarithmic_error: 0.0140 - val_loss: 0.0480 - val_mean_squared_logarithmic_error: 0.0480
Epoch 5/150
404/404 [==============================] - 1s 2ms/step - loss: 0.0140 - mean_squared_logarithmic_error: 0.0140 - val_loss: 0.0498 - val_mean_squared_logarithmic_error: 0.0498
Epoch 6/150
404/404 [==============================] - 1s 2ms/ste

In [ ]:
prediction=model_NN.predict(X_test)

In [ ]:
prediction

array([[24.826365 ],
       [23.912764 ],
       [23.126709 ],
       [11.559817 ],
       [18.803068 ],
       [18.97487  ],
       [23.152943 ],
       [22.000607 ],
       [17.95646  ],
       [11.357902 ],
       [ 9.630702 ],
       [12.963051 ],
       [13.635058 ],
       [10.552457 ],
       [39.706875 ],
       [34.27452  ],
       [25.76583  ],
       [39.807693 ],
       [28.59053  ],
       [22.155958 ],
       [24.222553 ],
       [22.383492 ],
       [19.41945  ],
       [26.682543 ],
       [21.073019 ],
       [18.56223  ],
       [17.452272 ],
       [16.136986 ],
       [44.436924 ],
       [19.208225 ],
       [15.292809 ],
       [18.4099   ],
       [19.468534 ],
       [21.295322 ],
       [25.966167 ],
       [18.106827 ],
       [ 8.989462 ],
       [29.192076 ],
       [14.150711 ],
       [13.241858 ],
       [23.189634 ],
       [21.858109 ],
       [22.28338  ],
       [16.019806 ],
       [23.463518 ],
       [23.88455  ],
       [17.31053  ],
       [10.29

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
DNN_pred=model_NN.predict(X_test)
DNN_pred=(DNN_pred>0.5)
print("The confusion matrix of Logistic regression \n", confusion_matrix(Y_test,DNN_pred))
print("The classification report of Logistic regression is \n", classification_report(Y_test,DNN_pred))


The confusion matrix of Logistic regression 
 [[64  3]
 [ 3 44]]
The classification report of Logistic regression is 
               precision    recall  f1-score   support

           0       0.96      0.96      0.96        67
           1       0.94      0.94      0.94        47

    accuracy                           0.95       114
   macro avg       0.95      0.95      0.95       114
weighted avg       0.95      0.95      0.95       114

